# Generated by Django 4.2.7 on 2023-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
