# Generated by Django 4.2.5 on 2023-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
