# Generated by Django 4.2.7 on 2023-12-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_game_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_gameplayed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
