# Generated by Django 4.2.7 on 2024-01-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user_game_won_profile_user_gameplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_symbol',
            field=models.CharField(default='Pastel', max_length=255),
        ),
    ]
