# Generated by Django 4.2.7 on 2023-11-17 21:04

import Game.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(default=Game.models.generate_random_code, max_length=11, unique=True)),
                ('X_parameter', models.IntegerField()),
                ('Y_parameter', models.IntegerField()),
                ('Private', models.BooleanField(default=False)),
                ('Alignment', models.IntegerField()),
                ('Player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1_games', to=settings.AUTH_USER_MODEL)),
                ('Player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_games', to=settings.AUTH_USER_MODEL)),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
