# Generated by Django 4.2.5 on 2023-11-17 09:32

import Game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(default=Game.models.generate_random_code, max_length=11, unique=True)),
                ('Private', models.BooleanField(default=False)),
                ('Grid_X', models.IntegerField()),
                ('Grid_Y', models.IntegerField()),
                ('Alignment', models.IntegerField()),
                ('Player_1', models.CharField(max_length=255)),
                ('Player_2', models.CharField(max_length=255)),
                ('Winner', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
