# Generated by Django 4.2.7 on 2023-12-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hasSurrend',
            field=models.BooleanField(default=False),
        ),
    ]
