# Generated by Django 4.2.7 on 2023-11-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('value', models.CharField(default='', max_length=1)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Game.game')),
            ],
        ),
    ]
