# Generated by Django 4.2.7 on 2023-12-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_game_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
