# Generated by Django 4.2.7 on 2023-11-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game', '0005_alter_game_player_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(blank=True, db_column='player_2', default='null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
