# Generated by Django 4.2.7 on 2023-11-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=50)),
                ('PlayerFirstName', models.TextField()),
                ('PlayerLastName', models.TextField()),
                ('PlayerPassword', models.TextField()),
            ],
        ),
    ]
