# Generated by Django 4.2.7 on 2023-11-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelbMorpion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=50)),
                ('PlayerFirstName', models.TextField()),
                ('PlayerLastName', models.TextField()),
                ('PlayerPassword', models.TextField()),
                ('PlayerBirthDate', models.DateField()),
                ('PlayerScore', models.PositiveIntegerField()),
                ('PlayerEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
