# Generated by Django 4.2.7 on 2023-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelbMorpion', '0002_users_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='PlayerFirstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='PlayerLastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='PlayerPassword',
            field=models.CharField(max_length=500),
        ),
    ]
