# Generated by Django 4.2.7 on 2023-11-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelbMorpion', '0003_alter_users_playerfirstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
