# Generated by Django 4.2.7 on 2023-11-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelbMorpion', '0004_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
