# Generated by Django 4.2.7 on 2024-01-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelbMorpion', '0007_communitymessage_hasbeentreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymessage',
            old_name='hasbeentreated',
            new_name='has_been_treated',
        ),
    ]
